language: cpp
dist: bionic
compiler:
  - gcc
  # - clang 

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default
  # Wt
  #- sudo ./install_wt
  # cppcheck
  - sudo apt-get install -qq cppcheck
  # Codecov
  - sudo pip install codecov
  # OCLint
  - ./install_oclint
  # Others
  - ./download_other_githubs

services:
 - xvfb

script: 
  # Test console
  - qmake -qt=qt5 AsciiArterConsoleTest.pro
  - make --silent debug
  - ./AsciiArterConsoleTest
  # Test desktop
  - qmake -qt=qt5 AsciiArterDesktopTest.pro
  - make --silent debug
  - ./AsciiArterDesktopTest
  # Desktop
  - qmake -qt=qt5 AsciiArterDesktop.pro
  - make --silent debug
  - ./AsciiArterDesktop &
  # Console
  - qmake -qt=qt5 AsciiArterConsole.pro
  - make --silent debug
  - ./AsciiArterConsole --help
  # Website
  #- qmake -qt=qt5 AsciiArterWebsite.pro
  #- make --silent debug
  #- ./AsciiArterWebsite &
  # cppcheck, accept memory leak for now
  - cppcheck --quiet --error-exitcode=0 . 
  # Code coverage
  - ./get_code_cov >/dev/null
  - codecov >/dev/null
  # OCLint
  - ./do_oclint

after_success:
  - bash <(curl -s https://codecov.io/bash)


